### ISSUE TITLE
No longer launches with newest Serene Seasons 1.16.5

### ISSUE THREAD

**Issue by NighthowlerStudios** [123oro321/sereneseasonsfix#2]
an update to Serene Seasons was published a few days ago, and the dependency.json will not permit the patch to load.  please change the json to assume future versions are working as 1.16.5 support has been dropped beyond crash and bug fixes.

the new version: 4.0.1.127
this mod version: 1.0.4
error message: "serene seasons fix is incompatible with serene seasons.  please use 4.0.1.126 or below."

**Comment by 123oro321** [comment]
Just uploaded a fix to that, should accept all revisions above 125.
Will upload soon similar fix for 1.18 and 1.17.
