### ISSUE TITLE
1.19 version

### ISSUE THREAD

**Issue by Nouwan** [123oro321/sereneseasonsfix#4]
Hi, I saw there was a 1.19 branch is there a 1.19 version yet?

**Comment by 123oro321** [comment]
I started porting but ditched it since there was no demand. I will give it another try the next few weeks.

**Comment by Nouwan** [comment]
That would be amazing. Its mainly the performance issues for us. We use serene seasons with hourglass but had to ditch it due to huge tps lag and we hope that this fix mod will improve performance so that we can add it again. 

I profiled with spark profiler when we had serene seasons added: 
You can se here that it used 29ms during some ticks.
https://spark.lucko.me/NkgPv1IBf0

**Comment by 123oro321** [comment]
Interesting. I didn't try to run profiler with the mods, so i can't guarantee it will make any difference on that aspect. However i do know it should prevent memory leak (but it's very negligible) and i prevent excessive logging which might have a slight performance improvement. I will be very glad if you could report to me if you see any improvement. I will upload the new version within an hour max.

**Comment by 123oro321** [comment]
I uploaded the new version and it should be available in the next few minutes through the website.
It usually takes few hours to appear on the launcher.
I will be glad for a follow-up with an update whenever it helped your performance problem or not.

**Comment by Nouwan** [comment]
That's awesome. Sadly, I have fallen i'll this week once I recover, I’ll test it on our server and post the profile results here.
