### ISSUE TITLE
world time doesnt sync

### ISSUE THREAD

**Issue by PatriotCZ** [123oro321/sereneseasonsfix#9]
Versions
Minecraft 1.20.1
Serene Seasons 9.0.0.46
Season fix 1.1.0.1
Hourglass 1.2.1.1

Time on newly created worlds matches the world and season time exactly 

time on my played world differ vastly: World time 2363928 while season time is 59928

when using /season time sync the number sets itself to 59928, although I can set different values like 200000 no problem

Delta in both instances is 0: so it might be ok, I am not really sure whether this is an issue, but seeing that on other worlds the numbers match exactly I suspect something is wrong.

**Comment by 123oro321** [comment]
It is the intended behavior.
World time is unlimited (besides the obvious integer limit), unlike season time which is capped by the value of a whole "year",
By default its `12 (sub seasons) * 8 (days per season) * 24000 (ticks in day) = 2304000 ticks`.
It means after a year it will reset back to 0, and therefore a new year begins.
Knowing this, if we subtract your world time with season time, we get exactly 1 year, so the delta is correct and the times are correctly synced.
